name: Andrew DeLozier Photography
favicon: null
layout_spectrum: 0.99671
typography_spectrum: 0.90987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e1118'
    - '#fffefe'
    - '#778189'
    - '#a7afb2'
    - '#c4d1df'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
